from django.conf.urls.defaults import patterns
from views import *


urlpatterns = patterns('',
	(r'^$', presence),
	(r'^panel/$', panel),
	(r'^error/(\d+)/$', error),
	(r'^accounts/login/$',  entrar),
	(r'^accounts/logout/$', salir),
	(r'^cambio/$', cambioPassword),
	(r'^registroAlumno/$', registroAlumno),
	(r'^registroEmpresa/$', registroEmpresa),
	(r'^editarEmpresa/(\d+)/$', editarEmpresa),
	(r'^registroLaboral/(\d+)?/?$', registroLaboral),
	(r'^verLaborals/(\d+)?/?$', verLaborals),
	(r'^editarLaboral/(\d+)/$', editarLaboral),
	(r'^registroDocente/$', registroDocente),
	(r'^registroCompleto/$', registroCompleto),
	(r'^FichaPdf/$', FichaPdf),
	(r'^insertarSeguimiento/$', insertarSeguimiento),
	(r'^editarSeguimiento/(\d+)/$', editarSeguimiento),
	(r'^verSeguimiento/(\d+)?/?$', verSeguimiento),
	(r'^borrarSeguimiento/(\d+)/$', borrarSeguimiento),
	(r'^verEmpresas/$', verEmpresas),
	(r'^verAlumnos/$', verAlumnos),
	(r'^verDocentes/$', verDocentes),
	(r'^ProgramaPdf/(\S+)/$', ProgramaPdf),
	(r'^ContratoPdf/(\S+)/$', ContratoPdf),
	(r'^verContratos/(\d+)?/?$', verContratos),
	(r'^verContrato/(\d+)/$', verContrato),
	(r'^crearContrato/(\d+)/$', crearContrato),
	(r'^editarContrato/(\d+)/$', editarContrato),
	(r'^crearGerente/(\d+)/$', crearGerente),
	(r'^editarGerente/(\d+)/$', editarGerente),
	(r'^verGerentes/(\d+)/$', verGerentes),
	(r'^verCentros/(\d+)?/?$', verCentros),
	(r'^crearCentro/(\d+)?/?$', crearCentro),
	(r'^editarCentro/(\d+)/$', editarCentro),
	(r'^verAlumnosEmpresa/(\d+)/$', verAlumnosEmpresa),
	(r'^activaUsuario/(\d+)/$', activaUsuario),
	(r'^desactivaUsuario/(\d+)/$', desactivaUsuario),
	(r'^hablaUsuario/(\d+)/$', hablaUsuario),
	(r'^nohablaUsuario/(\d+)/$', nohablaUsuario),
	(r'^updateUser/$', updateUser),
	(r'^updateComplete/$', updateComplete),
	(r'^confirmaContrato/(\d+)/$', confirmaContrato),
	(r'^desconfirmaContrato/(\d+)/$', desconfirmaContrato),
	(r'^crearVisita/(\d+)/$', crearVisita),
	(r'^editarVisita/(\d+)/$', editarVisita),
	(r'^verVisitas/(\d+)?/?$', verVisitas),
	(r'^verVisita/(\d+)/$', verVisita),
	(r'^VisitaPdf/(\S+)/$', VisitaPdf),
	(r'^verVisitasAlu/(\d+)/$', verVisitasAlu),
	(r'^crearVisitaAlu/(\d+)/$', crearVisitaAlu),
	(r'^borrarVisita/(\d+)/$', borrarVisita),
	(r'^activar/(\S+)/$', activar),
	(r'^norecuerdo/$', restaurarPassword),
)
